services:
  - type: web
    name: termocatalog
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn catalog.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.10"
