# Generated by Django 3.1.7 on 2021-04-17 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='photo_1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/about/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='photo_2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/about/'),
            preserve_default=False,
        ),
    ]
