# Generated by Django 3.1.7 on 2022-01-30 00:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sandblast', models.ImageField(upload_to='photos/designs/')),
                ('printing', models.ImageField(upload_to='photos/designs/')),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'designsPage',
            },
        ),
    ]
