# Generated by Django 3.1.7 on 2023-01-07 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_designspage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpage',
            old_name='email',
            new_name='primary_email',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='unit',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='secondary_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
