# Generated by Django 3.1.7 on 2021-04-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210417_0355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name_plural': 'aboutPage'},
        ),
    ]
