# Generated by Django 3.1.7 on 2023-01-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20230107_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designspage',
            name='printing',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='designspage',
            name='sandblast',
            field=models.CharField(max_length=250),
        ),
    ]
