# Generated by Django 3.1.7 on 2023-03-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20230108_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='photo_1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='photo_2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.CharField(max_length=250),
        ),
    ]
