# Generated by Django 3.1.7 on 2021-05-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210426_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='photos/about/partners/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='faqpage',
            options={'verbose_name': 'faq', 'verbose_name_plural': 'faqPage'},
        ),
    ]
