# Generated by Django 3.1.7 on 2022-01-29 19:41

import categories.models
import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_img', models.ImageField(help_text='Dimensiuni recomandate: ', upload_to=categories.models.category_dir_path)),
                ('description', ckeditor.fields.RichTextField()),
                ('youtube_link', models.CharField(blank=True, max_length=250)),
                ('external_link', models.CharField(blank=True, max_length=250)),
                ('relevance', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
            managers=[
                ('sorted_by_relevance', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=categories.models.gallery_dir_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
    ]
