# Generated by Django 3.1.7 on 2022-04-16 13:42

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_img',
            field=models.ImageField(upload_to=categories.models.category_dir_path),
        ),
    ]
