# Generated by Django 3.1.7 on 2023-01-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20230108_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.CharField(max_length=250),
        ),
    ]
