# Generated by Django 3.1.7 on 2021-05-15 23:12

import django.core.validators
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20210515_1517'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('sorted_by_relevance', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='relevance',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
