# Generated by Django 3.1.7 on 2022-01-30 00:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_auto_20220129_2328'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sandblast',
            managers=[
                ('sorted_by_size', django.db.models.manager.Manager()),
            ],
        ),
    ]
