# Generated by Django 3.1.7 on 2022-04-16 14:33

import designs.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_auto_20220130_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=designs.models.product_dir_path_pr)),
                ('wide', models.BooleanField(default=False)),
                ('high', models.BooleanField(default=False)),
            ],
            managers=[
                ('sorted_by_size', django.db.models.manager.Manager()),
            ],
        ),
    ]
