# Generated by Django 3.1.7 on 2023-01-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_printing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandblast',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
