# Generated by Django 3.1.7 on 2023-01-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_auto_20230108_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printing',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
