# Generated by Django 3.1.7 on 2021-05-15 23:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0005_auto_20210516_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_img', models.ImageField(help_text='Dimensiuni recomandate: ', upload_to=products.models.product_dir_path)),
                ('description', ckeditor.fields.RichTextField()),
                ('youtube_link', models.CharField(blank=True, max_length=250)),
                ('external_link', models.CharField(blank=True, max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
    ]
