# Generated by Django 3.1.7 on 2023-01-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display_img',
            field=models.CharField(max_length=250),
        ),
    ]
