# Generated by Django 3.1.7 on 2023-04-02 19:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230402_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
